name: Test Schedule
on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
    # Runs every 2 minutes for testing
    - cron: '*/5 * * * *'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Scheduled test is working at $(date)"